### ISSUE TITLE
Práctica 5 | No entiendo esta parte del enunciado

### ISSUE THREAD

**Issue by Senen19** [antroher/practica_dwec_gestor_presupuesto#119]
Hola, no entiendo esta parte del enunciado de la práctica 5 que corresponde a la función EditarHandle:

`La función EditarHandle será una función constructora que definirá exclusivamente un método llamado handleEvent. Cuando creemos un objeto basado en su prototipo, asignaremos a dicho objeto una propiedad llamada gasto, que será una referencia al gasto que estemos editando. El código de la función handleEvent podrá hacer referencia a dicho gasto a través de this.gasto, ya que es una propiedad del objeto. `

Sin poder hacer esto no puedo avanzar en los ejercicios.

**Comment by eurame** [comment]
Creo que tu función EditarHandle está bien planteada. Ahora deberíamos llamar, desde el gasto a modificar (su botón) al método addEventListener. Aquí tienes un ejemplo de uso:

![image](https://user-images.githubusercontent.com/91950536/140498628-2ff99d29-f94c-4021-b5ae-4e3cfd660fd2.png)

**Comment by eurame** [comment]
![image](https://user-images.githubusercontent.com/91950536/140505347-f7feaa9d-88fb-4e5e-b3f9-8ca31fa33b83.png)

**Comment by antroher** [comment]
Creo que tu función EditarHandle está bien planteada. Ahora deberíamos llamar, desde el gasto a modificar (su botón) al método addEventListener. Aquí tienes un ejemplo de uso:

![image](https://user-images.githubusercontent.com/91950536/140498628-2ff99d29-f94c-4021-b5ae-4e3cfd660fd2.png)

Vamos, que en tu código es cada elemento html que se va seleccionando al que hay que asignarle un manejador:

![imagen](https://user-images.githubusercontent.com/38523062/140505671-dcedf90f-e1b4-49db-9386-59f4216804c2.png)

**Comment by eurame** [comment]
![code](https://user-images.githubusercontent.com/91950536/140517421-53ccc903-ff73-4f8c-994c-50e837641354.png)

**Comment by antroher** [comment]
![code](https://user-images.githubusercontent.com/38523062/140517507-d99a0ae5-afe1-464c-842c-a2d8e2a1568c.png)

**Comment by antroher** [comment]
A ver si este código te ayuda:

creación de botón en función mostrarGastoWeb
![imagen](https://user-images.githubusercontent.com/38523062/140711405-7fcf3147-6834-4d1d-9618-a00f7fbf1d0f.png)

Creación del objeto para pasarle al manejador, con el gasto actual
![imagen](https://user-images.githubusercontent.com/38523062/140711593-85c221aa-b667-46b4-b2ac-3a1f9f15398f.png)

añadimos al DOM el botón
![imagen](https://user-images.githubusercontent.com/38523062/140711716-0e0c6a79-673f-471e-b5e6-642efee69f12.png)

función EditarHandle
![imagen](https://user-images.githubusercontent.com/38523062/140711823-56be5920-0ec8-4668-ad7e-3442c7f881ea.png)

**Comment by antroher** [comment]
Finalizado
